# -*- coding: utf-8 -*-
"""캡디1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15bK3huiOTFEPv_dee2Rx1D7LHdcBEjLQ
"""

# 1. 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

# 2. 최신 YOLO 라이브러리 설치
!pip install ultralytics

import os

# 1. 드라이브의 zip 파일을 코랩으로 복사
!cp "/content/drive/MyDrive/VOC2028.zip" .

# 2. VOCdevkit 폴더를 만들고 압축 해제
!mkdir -p ./VOCdevkit
!unzip -q VOC2028.zip -d ./VOCdevkit

# 3. 폴더 구조 확인 (이때 Annotations 폴더 위치가 중요합니다)
!ls -R ./VOCdevkit | grep ":$" | head -n 5

import os
import xml.etree.ElementTree as ET
import glob

def convert_to_yolo():
    classes = ['hat', 'person']
    # XML 파일들 찾기
    xml_files = glob.glob('/content/VOCdevkit/**/Annotations/*.xml', recursive=True)

    if not xml_files:
        print("XML 파일을 찾지 못했습니다. 경로를 확인하세요.")
        return

    # labels 폴더 생성 위치 파악
    base_dir = os.path.dirname(os.path.dirname(xml_files[0]))
    txt_path = os.path.join(base_dir, 'labels')
    os.makedirs(txt_path, exist_ok=True)

    count = 0
    for xml_file in xml_files:
        tree = ET.parse(xml_file)
        root = tree.getroot()
        size = root.find('size')
        w, h = int(size.find('width').text), int(size.find('height').text)

        with open(os.path.join(txt_path, os.path.basename(xml_file).replace('.xml', '.txt')), 'w') as f:
            for obj in root.iter('object'):
                cls = obj.find('name').text
                if cls not in classes: continue
                cls_id = classes.index(cls)
                xmlbox = obj.find('bndbox')
                b = (float(xmlbox.find('xmin').text), float(xmlbox.find('xmax').text),
                     float(xmlbox.find('ymin').text), float(xmlbox.find('ymax').text))
                # YOLO 형식 좌표 변환 (중심X, 중심Y, 너비, 높이)
                bb = ((b[0]+b[1])/2.0/w, (b[2]+b[3])/2.0/h, (b[1]-b[0])/w, (b[3]-b[2])/h)
                f.write(f"{cls_id} {' '.join([f'{a:.6f}' for a in bb])}\n")
        count += 1
    print(f"✅ 성공: {count}개의 파일을 {txt_path}에 변환 저장했습니다.")
    return base_dir

# 🚀 함수 실행
data_root = convert_to_yolo()

import yaml

# 이미지 오른쪽 결과와 동일하게 설정값 변경
data_config = {
    'path': '/content/dataset',  # data_root 대신 직접 경로 입력 (또는 해당 경로로 설정)
    'train': 'images',           # JPEGImages를 images로 변경
    'val': 'images',             # JPEGImages를 images로 변경
    'names': {
        0: 'hat',
        1: 'person'
    }
}

# YAML 파일 저장
# sort_keys=False를 추가하면 딕셔너리 순서가 그대로 유지되어 더 깔끔합니다.
with open('data.yaml', 'w') as f:
    yaml.dump(data_config, f, sort_keys=False)

print("data.yaml 파일이 성공적으로 생성되었습니다.")

!cat /content/data.yaml

# labels 폴더를 JPEGImages와 같은 레벨로 복사/이동
!cp -r /content/VOCdevkit/VOC2028/labels /content/VOCdevkit/VOC2028/JPEGImages_labels
# 또는 YOLO가 찾기 쉽게 images 폴더 바로 옆으로 옮기는 작업이 필요할 수 있습니다.

import os
import shutil

# 1. YOLO가 인식하기 가장 좋은 표준 구조 생성
os.makedirs('/content/dataset/images', exist_ok=True)
os.makedirs('/content/dataset/labels', exist_ok=True)

# 2. 사진 복사 (JPEGImages -> dataset/images)
!cp /content/VOCdevkit/VOC2028/JPEGImages/*.jpg /content/dataset/images/

# 3. 라벨 복사 (labels -> dataset/labels)
# 만약 labels 폴더 위치가 다르다면 실제 위치로 경로를 수정하세요.
!cp /content/VOCdevkit/VOC2028/labels/*.txt /content/dataset/labels/

print(f"✅ 사진 개수: {len(os.listdir('/content/dataset/images'))}")
print(f"✅ 라벨 개수: {len(os.listdir('/content/dataset/labels'))}")

from ultralytics import YOLO

# 1. 최신 YOLO 모델 로드
model = YOLO('best.pt')

# 2. 학습 시작 (device=0은 GPU 사용)
model.train(data='/content/data.yaml', epochs=5, imgsz=416, device=0)

from ultralytics import YOLO
import os

def check_helmet(image_path):
    # 1. 학습된 최적의 모델 불러오기
    # 학습이 끝났다면 runs/detect/train/weights/best.pt에 저장되어 있습니다.
    model_path = '/content/runs/detect/train/weights/best.pt'

    if not os.path.exists(model_path):
        print("모델 파일을 찾을 수 없습니다. 학습이 먼저 완료되어야 합니다.")
        return

    model = YOLO(model_path)

    # 2. 이미지 분석 (conf는 신뢰도 임계값입니다)
    results = model.predict(source=image_path, conf=0.4, save=False, verbose=False)

    # 3. 결과 분석
    helmet_detected = False
    for r in results:
        # 감지된 객체들의 클래스 ID 확인
        # 2번 셀에서 'hat'을 0번 클래스로 설정했으므로, 0이 있는지 확인합니다.
        for box in r.boxes:
            class_id = int(box.cls[0])
            if class_id == 0:  # 0: 'hat' (헬멧)
                helmet_detected = True
                break

    # 4. Y / N 출력
    if helmet_detected:
        print("Y")
    else:
        print("N")

# 테스트 실행 (파일명을 실제 분석할 사진 이름으로 바꾸세요)
check_helmet('1.jpg')

check_helmet('2.jpg')
check_helmet('3.jpg')
check_helmet('4.jpg')
check_helmet('5.jpg')
check_helmet('6.jpg')
